---
name: Welcome to EST Clock Discussions
about: Please read this before starting a new discussion
---

Welcome to EST Clock Discussions! 👋

This is a place for:
- Feature suggestions and ideas
- Questions about using EST Clock
- Sharing how you use EST Clock
- General feedback and community chat

Before posting:
- Search existing discussions to avoid duplicates
- For bugs, please use the Issues section instead
- Be respectful and follow our Code of Conduct

Choose the appropriate category for your discussion:
- 💡 Ideas: For feature requests and suggestions
- 🤔 Q&A: For questions about using EST Clock
- 💬 General: For general discussion and feedback