name: Main Branch CI

on:
  push:
    branches: [ main ]

# Set permissions for the GITHUB_TOKEN
permissions:
  contents: write  # This is required for creating releases

jobs:
  build-test-prerelease:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
          version: 12.2.0

      - name: Build application
        shell: cmd
        run: |
          build.bat

      - name: Verify build output
        run: dir build

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Build and Run Tests
        run: |
          cd tests
          mkdir -p build
          cd build
          cmake ..
          cmake --build . --config Debug
          ./Debug/time_conversion_tests.exe
          ./Debug/time_zone_conversion_tests.exe
        shell: bash

      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Get short SHA
        id: sha
        run: echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Create Pre-release
        uses: softprops/action-gh-release@v1
        with:
          files: build/windows-est-clock-portable.exe
          draft: false
          prerelease: true
          tag_name: nightly-${{ steps.date.outputs.DATE }}-${{ steps.sha.outputs.SHA }}
          name: Development Build ${{ steps.date.outputs.DATE }}
          body: |
            ## Development Build ${{ steps.date.outputs.DATE }}
            
            This is an automated development build from the latest code in the main branch.
            
            **Commit:** ${{ steps.sha.outputs.SHA }}
            
            ### Installation
            1. Download the `windows-est-clock-portable.exe` file
            2. Double-click to run (no installation required)
            
            ### Warning
            This is a development build and may contain bugs or unfinished features.
            For stable releases, please use the latest versioned release.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
